/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
    "payload-mcp-api-keys": PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    docs: Doc;
    exports: Export;
    imports: Import;
    "payload-mcp-api-keys": PayloadMcpApiKey;
    search: Search;
    "payload-kv": PayloadKv;
    "payload-jobs": PayloadJob;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    "payload-mcp-api-keys":
      | PayloadMcpApiKeysSelect<false>
      | PayloadMcpApiKeysSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
  locale: null;
  user: User | PayloadMcpApiKey;
  widgets: {
    collections: CollectionsWidget;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  collection: "users";
  createdAt: string;
  email: string;
  hash?: string | null;
  id: string;
  lockUntil?: string | null;
  loginAttempts?: number | null;
  name: string;
  password?: string | null;
  resetPasswordExpiration?: string | null;
  resetPasswordToken?: string | null;
  /**
   * Owner: Full system access. Admin: Can create users and content. User: Read-only access. Admins will automatically create users with 'user' role.
   */
  role?: ("owner" | "admin" | "user") | null;
  salt?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  alt: string;
  createdAt: string;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  height?: number | null;
  id: string;
  mimeType?: string | null;
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  width?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  createdAt: string;
  /**
   * Brief description of this documentation category
   */
  description?: string | null;
  /**
   * Icon image for the category
   */
  icon?: (string | null) | Media;
  id: string;
  /**
   * Order in which this category appears in the sidebar
   */
  order: number;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * The display title for this category/sidebar tab
   */
  title: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  _status?: ("draft" | "published") | null;
  /**
   * The sidebar tab/category this doc belongs to
   */
  category: string | Category;
  /**
   * The main content of the documentation page
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  createdAt: string;
  /**
   * Brief description or excerpt for this page
   */
  description?: string | null;
  id: string;
  /**
   * Order within the category/parent
   */
  order: number;
  /**
   * Parent page for nested documentation structure
   */
  parent?: (string | null) | Doc;
  /**
   * URL-friendly identifier for this page
   */
  slug: string;
  /**
   * The page title
   */
  title: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  collectionSlug: string;
  createdAt: string;
  drafts?: ("yes" | "no") | null;
  fields?: string[] | null;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  format: "csv" | "json";
  height?: number | null;
  id: string;
  limit?: number | null;
  mimeType?: string | null;
  name?: string | null;
  page?: number | null;
  selectionToUse?: ("currentSelection" | "currentFilters" | "all") | null;
  sort?: string | null;
  sortOrder?: ("asc" | "desc") | null;
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  width?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  collectionSlug: string;
  createdAt: string;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  height?: number | null;
  id: string;
  importMode?: ("create" | "update" | "upsert") | null;
  matchField?: string | null;
  mimeType?: string | null;
  status?: ("pending" | "completed" | "partial" | "failed") | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  width?: number | null;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: "payload-mcp-api-keys";
  createdAt: string;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  docs?: {
    /**
     * Allow clients to find docs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create docs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update docs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete docs.
     */
    delete?: boolean | null;
  };
  enableAPIKey?: boolean | null;
  id: string;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  updatedAt: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  createdAt: string;
  description?: string | null;
  doc: {
    relationTo: "docs";
    value: string | Doc;
  };
  id: string;
  priority?: number | null;
  title?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id: string;
  key: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  completedAt?: string | null;
  createdAt: string;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | "inline"
          | "createCollectionExport"
          | "createCollectionImport"
          | "schedulePublish";
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: "failed" | "succeeded";
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  processing?: boolean | null;
  queue?: string | null;
  taskSlug?:
    | (
        | "inline"
        | "createCollectionExport"
        | "createCollectionImport"
        | "schedulePublish"
      )
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalTried?: number | null;
  updatedAt: string;
  waitUntil?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  createdAt: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "categories";
        value: string | Category;
      } | null)
    | ({
        relationTo: "docs";
        value: string | Doc;
      } | null)
    | ({
        relationTo: "payload-mcp-api-keys";
        value: string | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: "search";
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  id: string;
  updatedAt: string;
  user:
    | {
        relationTo: "users";
        value: string | User;
      }
    | {
        relationTo: "payload-mcp-api-keys";
        value: string | PayloadMcpApiKey;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  createdAt: string;
  id: string;
  key?: string | null;
  updatedAt: string;
  user:
    | {
        relationTo: "users";
        value: string | User;
      }
    | {
        relationTo: "payload-mcp-api-keys";
        value: string | PayloadMcpApiKey;
      };
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  batch?: number | null;
  createdAt: string;
  id: string;
  name?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdAt?: T;
  email?: T;
  hash?: T;
  lockUntil?: T;
  loginAttempts?: T;
  name?: T;
  resetPasswordExpiration?: T;
  resetPasswordToken?: T;
  role?: T;
  salt?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdAt?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  height?: T;
  mimeType?: T;
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  createdAt?: T;
  description?: T;
  icon?: T;
  order?: T;
  slug?: T;
  title?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  _status?: T;
  category?: T;
  content?: T;
  createdAt?: T;
  description?: T;
  order?: T;
  parent?: T;
  slug?: T;
  title?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  createdAt?: T;
  drafts?: T;
  fields?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  format?: T;
  height?: T;
  limit?: T;
  mimeType?: T;
  name?: T;
  page?: T;
  selectionToUse?: T;
  sort?: T;
  sortOrder?: T;
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  where?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  createdAt?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  height?: T;
  importMode?: T;
  matchField?: T;
  mimeType?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  apiKey?: T;
  apiKeyIndex?: T;
  createdAt?: T;
  description?: T;
  docs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  enableAPIKey?: T;
  label?: T;
  updatedAt?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  createdAt?: T;
  description?: T;
  doc?: T;
  priority?: T;
  title?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  data?: T;
  key?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  completedAt?: T;
  createdAt?: T;
  error?: T;
  hasError?: T;
  input?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  processing?: T;
  queue?: T;
  taskSlug?: T;
  taskStatus?: T;
  totalTried?: T;
  updatedAt?: T;
  waitUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  createdAt?: T;
  document?: T;
  globalSlug?: T;
  updatedAt?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  createdAt?: T;
  key?: T;
  updatedAt?: T;
  user?: T;
  value?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  batch?: T;
  createdAt?: T;
  name?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | "users"
      | "media"
      | "categories"
      | "docs"
      | "exports"
      | "imports";
    drafts?: ("yes" | "no") | null;
    exportCollection: string;
    fields?: string[] | null;
    format: "csv" | "json";
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ("draft" | "published") | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ("publish" | "unpublish") | null;
    locale?: string | null;
    doc?: {
      relationTo: "docs";
      value: string | Doc;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
